import sublime, sublime_plugin, sys
PYTHON_VERSION = sys.version_info
if PYTHON_VERSION[0] == 3:
    from SublimePapyrus import SublimePapyrus

    class PapyrusSkseMenuSuggestionsCommand(SublimePapyrus.PapyrusShowSuggestionsCommand):
        def get_items(self, **args):
            items = {
            "BarterMenu": "Barter",
            "Book Menu": "Book",
            "Console Native UI Menu": "Console native UI",
            "Console": "Console",
            "ContainerMenu": "Container",
            "Crafting Menu": "Crafting",
            "Credits Menu": "Credits",
            "Cursor Menu": "Cursor",
            "CustomMenu": "Custom",
            "Debug Text Menu": "Debug text",
            "Dialogue Menu": "Dialogue",
            "Fader Menu": "Fader",
            "FavoritesMenu": "Favorites",
            "GiftMenu": "Gift",
            "HUD Menu": "HUD",
            "InventoryMenu": "Inventory",
            "Journal Menu": "Journal",
            "Kinect Menu": "Kinect",
            "LevelUp Menu": "Level up",
            "Loading Menu": "Loading",
            "Lockpicking Menu": "Lockpicking",
            "MagicMenu": "Magic",
            "Main Menu": "Main menu",
            "MapMenu": "Map",
            "MessageBoxMenu": "Message box",
            "Mist Menu": "Mist",
            "Overlay Interaction Menu": "Overlay interaction",
            "Overlay Menu": "Overlay",
            "Quantity Menu": "Quantity",
            "RaceSex Menu": "Race (character creation)",
            "Sleep/Wait Menu": "Sleep/wait",
            "StatsMenu": "Stats",
            "TitleSequence Menu": "Title sequence",
            "Top Menu": "Top",
            "Training Menu": "Training",
            "Tutorial Menu": "Tutorial",
            "TweenMenu": "Tween"
            }
            return items

    class PapyrusSkseKeycodeSuggestionsCommand(SublimePapyrus.PapyrusShowSuggestionsCommand):
        def get_items(self, **args):
            items = {
            1: "Escape",
            2: "1",
            3: "2",
            4: "3",
            5: "4",
            6: "5",
            7: "6",
            8: "7",
            9: "8",
            10: "9",
            11: "0",
            12: "Minus",
            13: "Equals",
            14: "Backspace",
            15: "Tab",
            16: "Q",
            17: "W",
            18: "E",
            19: "R",
            20: "T",
            21: "Y",
            22: "U",
            23: "I",
            24: "O",
            25: "P",
            26: "Left Bracket",
            27: "Right Bracket",
            28: "Enter",
            29: "Left Control",
            30: "A",
            31: "S",
            32: "D",
            33: "F",
            34: "G",
            35: "H",
            36: "J",
            37: "K",
            38: "L",
            39: "Semicolon",
            40: "Apostrophe",
            41: "Tilde",
            42: "Left Shift",
            43: "Back Slash",
            44: "Z",
            45: "X",
            46: "C",
            47: "V",
            48: "B",
            49: "N",
            50: "M",
            51: "Comma",
            52: "Period",
            53: "Forward Slash",
            54: "Right Shift",
            55: "NUM*",
            56: "Left Alt",
            57: "Spacebar",
            58: "Caps Lock",
            59: "F1",
            60: "F2",
            61: "F3",
            62: "F4",
            63: "F5",
            64: "F6",
            65: "F7",
            66: "F8",
            67: "F9",
            68: "F10",
            69: "Num Lock",
            70: "Scroll Lock",
            71: "NUM7",
            72: "NUM8",
            73: "NUM9",
            74: "NUM-",
            75: "NUM4",
            76: "NUM5",
            77: "NUM6",
            78: "NUM+",
            79: "NUM1",
            80: "NUM2",
            81: "NUM3",
            82: "NUM0",
            83: "NUM.",
            87: "F11",
            88: "F12",
            156: "NUM Enter",
            157: "Right Control",
            181: "NUM/",
            184: "Right Alt",
            199: "Home",
            200: "Up Arrow",
            201: "Page Up",
            203: "Left Arrow",
            205: "Right Arrow",
            207: "End",
            208: "Down Arrow",
            209: "Page Down",
            210: "Insert",
            211: "Delete",
            256: "Left Mouse Button",
            257: "Right Mouse Button",
            258: "Middle/Wheel Mouse Button",
            259: "Mouse Button 3",
            260: "Mouse Button 4",
            261: "Mouse Button 5",
            262: "Mouse Button 6",
            263: "Mouse Button 7",
            264: "Mouse Wheel Up",
            265: "Mouse Wheel Down",
            266: "D-pad Up (Gamepad)",
            267: "D-pad Down (Gamepad)",
            268: "D-pad Left (Gamepad)",
            269: "D-pad Right (Gamepad)",
            270: "Start (Gamepad)",
            271: "Back (Gamepad)",
            272: "Left thumbstick (Gamepad)",
            273: "Right thumbstick (Gamepad)",
            274: "Left shoulder (Gamepad)",
            275: "Right shoulder (Gamepad)",
            276: "A (Gamepad)",
            277: "B (Gamepad)",
            278: "X (Gamepad)",
            279: "Y (Gamepad)",
            280: "Left trigger (Gamepad)",
            281: "Right trigger (Gamepad)"
            }
            return items

    class PapyrusSkseControlSuggestionsCommand(SublimePapyrus.PapyrusShowSuggestionsCommand):
        def get_items(self, **args):
            items = {
            "Activate": "Activate",
            "Auto-Move": "Auto-move",
            "Back": "Back",
            "CameraPath": "Camera Path",
            "Console": "Console",
            "Favorites": "Favorites",
            "Forward": "Forward",
            "Hotkey1": "Hotkey 1",
            "Hotkey2": "Hotkey 2",
            "Hotkey3": "Hotkey 3",
            "Hotkey4": "Hotkey 4",
            "Hotkey5": "Hotkey 5",
            "Hotkey6": "Hotkey 6",
            "Hotkey7": "Hotkey 7",
            "Hotkey8": "Hotkey 8",
            "Journal": "Journal",
            "Jump": "Jump",
            "Left Attack/Block": "Left Attack/Block",
            "Look": "Look",
            "Move": "Move",
            "Multi-Screenshot": "Multi-screenshot",
            "Pause": "Pause",
            "Quick Inventory": "Quick Inventory",
            "Quick Magic": "Quick Magic",
            "Quick Map": "Quick Map",
            "Quick Stats": "Quick Stats",
            "Quickload": "Quick Load",
            "Quicksave": "Quick Save",
            "Ready Weapon": "Ready Weapon",
            "Right Attack/Block": "Right Attack/Block",
            "Run": "Run",
            "Screenshot": "Screenshot",
            "Shout": "Shout",
            "Sneak": "Sneak",
            "Sprint": "Sprint",
            "Strafe Left": "Strafe Left",
            "Strafe Right": "Strafe Right",
            "Toggle Always Run": "Toggle Always Run",
            "Toggle POV": "Toggle POV",
            "Tween Menu": "Tween Menu",
            "Wait": "Wait",
            "Zoom In": "Zoom In",
            "Zoom Out": "Zoom Out"
            }
            return items

    class PapyrusSkseDefaultObjectSuggestionsCommand(SublimePapyrus.PapyrusShowSuggestionsCommand):
        def get_items(self, **args):
            items = {
            "WWSP": "Werewolf Spell",
            "SALT": "Sitting Angle Limit",
            "APSH": "Allow Player Shout",
            "GOLD": "Gold",
            "LKPK": "Lockpick",
            "SKLK": "SkeletonKey",
            "PFAC": "Player Faction",
            "GFAC": "Guard Faction",
            "DFMS": "Default Music",
            "BTMS": "Battle Music",
            "DTMS": "Death Music",
            "SCMS": "Success Music",
            "LUMS": "Level Up Music",
            "DCMS": "Dungeon Cleared Music",
            "PVMA": "Player Voice (Male)",
            "PVMC": "Player Voice (Male Child)",
            "PVFA": "Player Voice (Female)",
            "PVFC": "Player Voice (Female Child)",
            "EPDF": "Eat Package Default Food",
            "LHEQ": "LeftHand Equip",
            "RHEQ": "RightHand Equip",
            "EHEQ": "EitherHand Equip",
            "VOEQ": "Voice Equip",
            "POEQ": "Potion Equip",
            "EACA": "Every Actor Ability",
            "CACA": "Commanded Actor Ability",
            "DEIS": "Drug Wears Off Image Space",
            "DFTS": "Footstep Set",
            "DLMT": "Landscape Material",
            "DLZM": "Dragon Land Zone Marker",
            "DCZM": "Dragon Crash Zone Marker",
            "CSTY": "Combat Style",
            "PLST": "Default Pack List",
            "PWFD": "Wait-For-Dialogue Package",
            "LRTB": "LocRefType Boss",
            "VLOC": "Virtual Location",
            "PLOC": "PersistAll Location",
            "INVP": "Inventory Player",
            "PTNP": "Pathing Test NPC",
            "FPCS": "Favor Cost Small",
            "FPCM": "Favor Cost Medium",
            "FPCL": "Favor Cost Large",
            "FGPD": "Favor Gifts Per Day",
            "AASW": "Action Swim State Change",
            "AALK": "Action Look",
            "AALA": "Action LeftAttack",
            "AALD": "Action LeftReady",
            "AALR": "Action LeftRelease",
            "AALI": "Action LeftInterrupt",
            "AARA": "Action RightAttack",
            "AARD": "Action RightReady",
            "AARR": "Action RightRelease",
            "AARI": "Action RightInterrupt",
            "AADA": "Action DualAttack",
            "AADL": "Action DualRelease",
            "AAAC": "Action Activate",
            "AAJP": "Action Jump",
            "AAFA": "Action Fall",
            "AALN": "Action Land",
            "AASN": "Action Sneak",
            "AAVC": "Action Voice",
            "AAVD": "Action VoiceReady",
            "AAVR": "Action VoiceRelease",
            "AAVI": "Action VoiceInterrupt",
            "AAID": "Action Idle",
            "AAST": "Action Sprint Start",
            "AASP": "Action Sprint Stop",
            "AADR": "Action Draw",
            "AASH": "Action Sheath",
            "ALPA": "Action Left Power Attack",
            "AAPA": "Action Right Power Attack",
            "ADPA": "Action Dual Power Attack",
            "AAS1": "Action Stagger Start",
            "AABH": "Action Block Hit",
            "AABA": "Action Block Anticipate",
            "AARC": "Action Recoil",
            "AAR2": "Action Large Recoil",
            "AAB1": "Action Bleedout Start",
            "AAB2": "Action Bleedout Stop",
            "AAIS": "Action Idle Stop",
            "AAWH": "Action Ward Hit",
            "AAFQ": "Action Force Equip",
            "AASC": "Action Shield Change",
            "AAPS": "Action Path Start",
            "AAPE": "Action Path End",
            "AALM": "Action Large Movement Delta",
            "AAF1": "Action Fly Start",
            "AAF2": "Action Fly Stop",
            "AAH1": "Action Hover Start",
            "AAH2": "Action Hover Stop",
            "AABI": "Action Bumped Into",
            "AASS": "Action Summoned Start",
            "ATKI": "Action Talking Idle",
            "ALTI": "Action Listen Idle",
            "AADE": "Action Death",
            "AADW": "Action Death Wait",
            "AIDW": "Action Idle Warn",
            "AMST": "Action Move Start",
            "AMSP": "Action Move Stop",
            "ATRI": "Action Turn Right",
            "ATLE": "Action Turn Left",
            "ATSP": "Action Turn Stop",
            "AMFD": "Action Move Forward",
            "AMBK": "Action Move Backward",
            "AMLT": "Action Move Left",
            "AMRT": "Action Move Right",
            "ARAG": "Action Reset Animation Graph",
            "AKDN": "Action Knockdown",
            "AAGU": "Action Get Up",
            "ASID": "Action Idle Stop Instant",
            "ARGI": "Action Ragdoll Instant",
            "AWWS": "Action Waterwalk Start",
            "AREL": "Action Reload",
            "PUSG": "Pickup Sound Generic",
            "PDSG": "Putdown Sound Generic",
            "PUSW": "Pickup Sound Weapon",
            "PDSW": "Putdown Sound Weapon",
            "PUSA": "Pickup Sound Armor",
            "PDSA": "Putdown Sound Armor",
            "PUSB": "Pickup Sound Book",
            "PDSB": "Putdown Sound Book",
            "PUSI": "Pickup Sound Ingredient",
            "PDSI": "Putdown Sound Ingredient",
            "HVSS": "Harvest Sound",
            "HVFS": "Harvest Failed Sound",
            "WBSN": "Ward Break Sound",
            "WASN": "Ward Absorb Sound",
            "WDSN": "Ward Deflect Sound",
            "MFSN": "Magic Fail Sound",
            "SFSN": "Shout Fail Sound",
            "HFSD": "Heartbeat Sound Fast",
            "HSSD": "Heartbeat Sound Slow",
            "IMLH": "Imagespace - Low Health",
            "SCSD": "Soul Captured Sound",
            "NASD": "No-Activation Sound",
            "MMSD": "Map Menu Looping Sound",
            "DDSC": "Dialogue Voice Category",
            "NDSC": "Non-Dialogue Voice Category",
            "SFDC": "SFX To Fade In Dialogue Category",
            "PDMC": "Pause During Menu Category (Fade)",
            "PIMC": "Pause During Menu Category (Immediate)",
            "PDLC": "Pause During Loading Menu Category",
            "MDSC": "Music Sound Category",
            "SMSC": "Stats Mute Category",
            "SSSC": "Stats Music",
            "MTSC": "Master Sound Category",
            "TSSC": "Time Sensitive Sound Category",
            "DOP2": "Dialogue Output Model (3D)",
            "DOP3": "Dialogue Output Model (2D)",
            "POPM": "Player's Output Model (1st Person)",
            "P3OM": "Player's Output Model (3rd Person)",
            "IOPM": "Interface Output Model",
            "RVBT": "Reverb Type",
            "UWLS": "Underwater Loop Sound",
            "URVT": "Underwater Reverb Type",
            "HRSK": "Keyword - Horse",
            "UNDK": "Keyword - Undead",
            "NPCK": "Keyword - NPC",
            "KWBR": "Keyword - BeastRace",
            "KWDM": "Keyword - DummyObject",
            "KWGE": "Keyword - UseGeometryEmitter",
            "KWMS": "Keyword - MustStop",
            "KWUA": "Keyword - UpdateDuringArchery",
            "KWOT": "Keyword - Skip Outfit Items",
            "FTHD": "Male Face Texture Set: Head",
            "FTMO": "Male Face Texture Set: Mouth",
            "FTEL": "Male Face Texture Set: Eyes",
            "FTHF": "Female Face Texture Set: Head",
            "FTMF": "Female Face Texture Set: Mouth",
            "FTRF": "Female Face Texture Set: Eyes",
            "IMID": "ImageSpaceModifier for inventory menu.",
            "PTEM": "Package template",
            "MMCL": "Main Menu Cell",
            "DMWL": "Default MovementType: Walk",
            "DMRN": "Default MovementType: Run",
            "DMSW": "Default MovementType: Swim",
            "DMFL": "Default MovementType: Fly",
            "DMSN": "Default MovementType: Sneak",
            "DMSP": "Default MovementType: Sprint",
            "SPFK": "Keyword - Special Furniture",
            "FFFP": "Keyword - Furniture Forces 1st Person",
            "FFTP": "Keyword - Furniture Forces 3rd Person",
            "AFNP": "Keyword - Activator Furniture No Player",
            "TKGS": "Telekinesis Grab Sound",
            "TKTS": "Telekinesis Throw Sound",
            "WMWE": "World Map Weather",
            "HMPC": "Help Manual PC",
            "HMXB": "Help Manual XBox",
            "TKAM": "Keyword - Type Ammo",
            "TKAR": "Keyword - Type Armor",
            "TKBK": "Keyword - Type Book",
            "TKIG": "Keyword - Type Ingredient",
            "TKKY": "Keyword - Type Key",
            "TKMS": "Keyword - Type Misc",
            "TKSG": "Keyword - Type SoulGem",
            "TKWP": "Keyword - Type Weapon",
            "TKPT": "Keyword - Type Potion",
            "BENW": "Base Weapon Enchantment",
            "BENA": "Base Armor Enchantment",
            "BAPO": "Base Potion",
            "BAPS": "Base Poison",
            "DRAK": "Keyword - Dragon",
            "MVBL": "Keyword - Movable",
            "ABSE": "Art Object - Absorb Effect",
            "WEML": "Weapon Material List",
            "ARTL": "Armor Material List",
            "DIEN": "Keyword - Disallow Enchanting",
            "FTML": "Favor travel marker location",
            "LKHO": "Keyword - Hold Location",
            "CWOK": "Keyword - Civil War Owner",
            "CWNE": "Keyword - Civil War Neutral",
            "LRSO": "LocRefType - Civil War Soldier",
            "KWDO": "Keyword - ClearableLocation",
            "LRRD": "LocRefType - Resource Destructible",
            "HCLL": "FormList - Hair Color List",
            "CMPX": "Complex Scene Object",
            "RUSG": "Keyword - Reusable SoulGem",
            "ANML": "Keyword - Animal",
            "DAED": "Keyword - Daedra",
            "BEEP": "Keyword - Robot",
            "NRNT": "Keyword - Nirnroot",
            "FTGF": "Fighters' Guild Faction",
            "MGGF": "Mages' Guild Faction",
            "TVGF": "Thieves' Guild Faction",
            "DBHF": "Dark Brotherhood Faction",
            "JRLF": "Jarl Faction",
            "AWWW": "Bunny Faction",
            "PIVV": "Player Is Vampire Variable",
            "PIWV": "Player Is Werewolf Variable",
            "NMRD": "Road Marker",
            "SAT1": "Keyword - Scale Actor To 1.0",
            "VAMP": "Keyword - Vampire",
            "FORG": "Keyword - Forge",
            "COOK": "Keyword - Cooking Pot",
            "SMLT": "Keyword - Smelter",
            "TANN": "Keyword - Tanning Rack",
            "HBLK": "Help - Basic Lockpicking (PC)",
            "HBLX": "Help - Basic Lockpicking (Console)",
            "HBFG": "Help - Basic Forging",
            "HBCO": "Help - Basic Cooking",
            "HBML": "Help - Basic Smelting",
            "HBTA": "Help - Basic Tanning",
            "HBOC": "Help - Basic Object Creation",
            "HBEC": "Help - Basic Enchanting",
            "HBSM": "Help - Basic Smithing Weapon",
            "HBSA": "Help - Basic Smithing Armor",
            "HBAL": "Help - Basic Alchemy",
            "HBBR": "Help - Barter",
            "HBLU": "Help - Leveling up",
            "HBSK": "Help - Skills Menu",
            "HBMM": "Help - Map Menu",
            "HBJL": "Help - Journal",
            "HBLH": "Help - Low Health",
            "HBLM": "Help - Low Magicka",
            "HBLS": "Help - Low Stamina",
            "HBHJ": "Help - Jail",
            "HBFT": "Help - Teamate Favor",
            "HBWC": "Help - Weapon Charge",
            "HBFS": "Help - Favorites",
            "KHFL": "Kinect Help FormList",
            "HBFM": "Help - Flying Mount",
            "HBTL": "Help - Target Lock",
            "HBAT": "Help - Attack Target",
            "LSIS": "Imagespace - Load screen",
            "WMDA": "Keyword - Weapon Material Daedric",
            "WMDR": "Keyword - Weapon Material Draugr",
            "WMDH": "Keyword - Weapon Material DraugrHoned",
            "WMDW": "Keyword - Weapon Material Dwarven",
            "WMEB": "Keyword - Weapon Material Ebony",
            "WMEL": "Keyword - Weapon Material Elven",
            "WMFA": "Keyword - Weapon Material Falmer",
            "WMFH": "Keyword - Weapon Material FalmerHoned",
            "WMGL": "Keyword - Weapon Material Glass",
            "WMIM": "Keyword - Weapon Material Imperial",
            "WMIR": "Keyword - Weapon Material Iron",
            "WMOR": "Keyword - Weapon Material Orcish",
            "WMST": "Keyword - Weapon Material Steel",
            "WMWO": "Keyword - Weapon Material Wood",
            "WTBA": "Keyword - WeaponTypeBoundArrow",
            "AODA": "Keyword - Armor Material Daedric",
            "AODP": "Keyword - Armor Material Dragonplate",
            "AODS": "Keyword - Armor Material Dragonscale",
            "AODB": "Keyword - Armor Material Dragonbone",
            "AODW": "Keyword - Armor Material Dwarven",
            "AOEB": "Keyword - Armor Material Ebony",
            "AOEL": "Keyword - Armor Material Elven",
            "AOES": "Keyword - Armor Material ElvenSplinted",
            "AOFL": "Keyword - Armor Material FullLeather",
            "AOGL": "Keyword - Armor Material Glass",
            "AOHI": "Keyword - Armor Material Hide",
            "AOIM": "Keyword - Armor Material Imperial",
            "AOIH": "Keyword - Armor Material ImperialHeavy",
            "AOIR": "Keyword - Armor Material ImperialReinforced",
            "AOFE": "Keyword - Armor Material Iron",
            "AOIB": "Keyword - Armor Material IronBanded",
            "AOOR": "Keyword - Armor Material Orcish",
            "AOSC": "Keyword - Armor Material Scaled",
            "AOST": "Keyword - Armor Material Steel",
            "AOSP": "Keyword - Armor Material SteelPlate",
            "AOSK": "Keyword - Armor Material Stormcloak",
            "AOSD": "Keyword - Armor Material Studded",
            "GCK1": "Keyword - Generic Craftable Keyword 01",
            "GCK2": "Keyword - Generic Craftable Keyword 02",
            "GCK3": "Keyword - Generic Craftable Keyword 03",
            "GCK4": "Keyword - Generic Craftable Keyword 04",
            "GCK5": "Keyword - Generic Craftable Keyword 05",
            "GCK6": "Keyword - Generic Craftable Keyword 06",
            "GCK7": "Keyword - Generic Craftable Keyword 07",
            "GCK8": "Keyword - Generic Craftable Keyword 08",
            "GCK9": "Keyword - Generic Craftable Keyword 09",
            "GCKX": "Keyword - Generic Craftable Keyword 10",
            "JWLR": "Keyword - Jewelry",
            "KWCU": "Keyword - Cuirass",
            "LMHP": "Local Map Hide Plane",
            "SLDM": "Snow LOD Material",
            "SLHD": "Snow LOD Material (HD)",
            "ALDM": "Ash LOD Material",
            "ALHD": "Ash LOD Material (HD)",
            "DGFL": "DialogueFollower Quest",
            "PTFR": "PotentialFollower Faction",
            "AVWP": "Werewolf Available Perks",
            "AVVP": "Vampire Available Perks",
            "RIWR": "Werewolf Race",
            "RIVR": "Vampire Race",
            "RIVS": "Vampire Spells",
            "DMXL": "Dragon Mount No Land List",
            "PCMD": "Player Can Mount Dragon Here List",
            "FMYS": "Flying Mount - Allowed Spells",
            "FMNS": "Flying Mount - Disallowed Spells",
            "MNT2": "Keyword - Mount",
            "AIVC": "Verlet Cape",
            "FTNP": "Furniture Test NPC",
            "COEX": "Keyword - Conditional Explosion",
            "VFNC": "Vampire Feed No Crime Faction",
            "KWSP": "Skyrim - Worldspace",
            "ALBM": "Keyword - Armor Material Light Bonemold",
            "ALCH": "Keyword - Armor Material Light Chitin",
            "ALNC": "Keyword - Armor Material Light Nordic",
            "ALSM": "Keyword - Armor Material Light Stalhrim",
            "FMFF": "Flying Mount - Fly Fast Worldspaces",
            "AHBM": "Keyword - Armor Material Heavy Bonemold",
            "AHCH": "Keyword - Armor Material Heavy Chitin",
            "AHNC": "Keyword - Armor Material Heavy Nordic",
            "AHSM": "Keyword - Armor Material Heavy Stalhrim",
            "WPNC": "Keyword - Weapon Material Nordic",
            "WPSM": "Keyword - Weapon Material Stalhrim"
            }
            return items

    class PapyrusSkseActorValueInfoNameSuggestionsCommand(SublimePapyrus.PapyrusShowSuggestionsCommand):
        def get_items(self, **args):
            items = {
            "Aggression": "Aggression",
            "Confidence": "Confidence",
            "Energy": "Energy",
            "Morality": "Morality",
            "Mood": "Mood",
            "Assistance": "Assistance",
            "OneHanded": "One-handed",
            "TwoHanded": "Two-handed",
            "Marksman": "Marksman",
            "Block": "Block",
            "Smithing": "Smithing",
            "HeavyArmor": "Heavy armor",
            "LightArmor": "Light armor",
            "Pickpocket": "Pickpocket",
            "LockPicking": "Lockpicking",
            "Sneak": "Sneak",
            "Alchemy": "Alchemy",
            "SpeechCraft": "Speech",
            "Alteration": "Alteration",
            "Conjuration": "Conjuration",
            "Destruction": "Destruction",
            "Mysticism": "Mysticism",
            "Restoration": "Restoration",
            "Enchanting": "Enchanting",
            "Health": "Health",
            "Magicka": "Magicka",
            "Stamina": "Stamina",
            "HealRate": "Heal rate",
            "MagickaRate": "Magicka rate",
            "StaminaRate": "Stamina rate",
            "SpeedMult": "Speed multiplier",
            "InventoryWeight": "Inventory weight",
            "CarryWeight": "Carry weight",
            "CritChance": "Critical chance",
            "MeleeDamage": "Melee damage",
            "UnarmedDamage": "Unarmed damage",
            "Mass": "Mass",
            "VoicePoints": "Voice points",
            "VoiceRate": "Voice rate",
            "DamageResist": "Damage resistance",
            "PoisonResist": "Poison resistance",
            "FireResist": "Fire resistance",
            "ElectricResist": "Shock resistance",
            "FrostResist": "Frost resistance",
            "MagicResist": "Magic resistance",
            "NormalWeaponsResist": "Normal weapon resistance",
            "PerceptionCondition": "Perception condition",
            "EnduranceCondition": "Endurance condition",
            "LeftAttackCondition": "Left attack condition",
            "RightAttackCondition": "Right attack condition",
            "LeftMobilityCondition": "Left mobility condition",
            "RightMobilityCondition": "Right mobility condition",
            "BrainCondition": "Brain condition",
            "Paralysis": "Paralysis",
            "Invisibility": "Invisibility",
            "NightEye": "Night eye",
            "DetectLifeRange": "Detect life range",
            "WaterBreathing": "Water breathing",
            "WaterWalking": "Water walking",
            "IgnoreCrippleLimbs": "Ignore crippled limbs",
            "Fame": "Fame",
            "Infamy": "Infamy",
            "JumpingBonus": "Jumping bonus",
            "WardPower": "Ward power",
            "EquippedItemCharge": "Equipped item charge",
            "ArmorPerks": "Armor perks",
            "ShieldPerks": "Shield perks",
            "WardDeflection": "Ward deflection",
            "Variable01": "Variable 01",
            "Variable02": "Variable 02",
            "Variable03": "Variable 03",
            "Variable04": "Variable 04",
            "Variable05": "Variable 05",
            "Variable06": "Variable 06",
            "Variable07": "Variable 07",
            "Variable08": "Variable 08",
            "Variable09": "Variable 09",
            "Variable10": "Variable 10",
            "BowSpeedBonus": "Bow speed bonus",
            "FavorActive": "Favor active",
            "FavorsPerDay": "Favors per day",
            "FavorsPerDayTimer": "Favors per day timer",
            "EquippedStaffCharge": "Equipped staff charge",
            "AbsorbChance": "Absorb chance",
            "Blindness": "Blindness",
            "WeaponSpeedMult": "Weapon speed multiplier",
            "ShoutRecoveryMult": "Shout recovery multiplier",
            "BowStaggerBonus": "Bow stagger bonus",
            "Telekinesis": "Telekinesis",
            "FavorPointsBonus": "Favor points bonus",
            "LastBribedIntimidated": "Last bribed or intimidated",
            "LastFlattered": "Last flattered",
            "Muffled": "Muffled",
            "BypassVendorStolenCheck": "Bypass vendor stolen check",
            "BypassVendorKeywordCheck": "Bypass vendor keyword check",
            "WaitingForPlayer": "Waiting for player",
            "OneHandedMod": "One-handed modifier",
            "TwoHandedMod": "Two-handed modifier",
            "MarksmanMod": "Marksman modifier",
            "BlockMod": "Block modifier",
            "SmithingMod": "Smithing modifier",
            "HeavyArmorMod": "Heavy armor modifier",
            "LightArmorMod": "Light armor modifier",
            "PickPocketMod": "Pickpocket modifier",
            "LockPickingMod": "Lockpicking modifier",
            "SneakMod": "Sneak modifier",
            "AlchemyMod": "Alchemy modifier",
            "SpeechcraftMod": "Speech modifier",
            "AlterationMod": "Alteration modifier",
            "ConjurationMod": "Conjuration modifier",
            "DestructionMod": "Destruction modifier",
            "IllusionMod": "Illusion modifier",
            "RestorationMod": "Restoration modifier",
            "EnchantingMod": "Enchanting modifier",
            "OneHandedSkillAdvance": "One-handed skill advance",
            "TwoHandedSkillAdvance": "Two-handed skill advance",
            "MarksmanSkillAdvance": "Marksman skill advance",
            "BlockSkillAdvance": "Block skill advance",
            "SmithingSkillAdvance": "Smithing skill advance",
            "HeavyArmorSkillAdvance": "Heavy armor skill advance",
            "LightArmorSkillAdvance": "Light armor skill advance",
            "PickPocketSkillAdvance": "Pickpocket skill advance",
            "LockPickingSkillAdvance": "Lockpicking skill advance",
            "SneakSkillAdvance": "Sneak skill advance",
            "AlchemySkillAdvance": "Alchemy skill advance",
            "SpeechcraftSkillAdvance": "Speech skill advance",
            "AlterationSkillAdvance": "Alteration skill advance",
            "ConjurationSkillAdvance": "Conjuration skill advance",
            "DestructionSkillAdvance": "Destruction skill advance",
            "IllusionSkillAdvance": "Illusion skill advance",
            "RestorationSkillAdvance": "Restoration skill advance",
            "EnchantingSkillAdvance": "Enchanting skill advance",
            "LeftWeaponSpeedMult": "Left weapon speed multiplier",
            "DragonSouls": "Dragon souls",
            "CombatHealthRegenMult": "Combat health regeneration multiplier",
            "OneHandedPowerMod": "One-handed power modifier",
            "TwoHandedPowerMod": "Two-handed power modifier",
            "MarksmanPowerMod": "Marksman power modifier",
            "BlockPowerMod": "Block power modifier",
            "SmithingPowerMod": "Smithing power modifier",
            "HeavyArmorPowerMod": "Heavy armor power modifier",
            "LightArmorPowerMod": "Light armor power modifier",
            "PickPocketPowerMod": "Pickpocket power modifier",
            "LockPickingPowerMod": "Lockpicking power modifier",
            "SneakPowerMod": "Sneak power modifier",
            "AlchemyPowerMod": "Alchemy power modifier",
            "SpeechcraftPowerMod": "Speech power modifier",
            "AlterationPowerMod": "Alteration power modifier",
            "ConjurationPowerMod": "Conjuration power modifier",
            "DestructionPowerMod": "Destruction power modifier",
            "IllusionPowerMod": "Illusion power modifier",
            "RestorationPowerMod": "Restoration power modifier",
            "EnchantingPowerMod": "Enchanting power modifier",
            "DragonRend": "Dragon Rend",
            "AttackDamageMult": "Attack damage multiplier",
            "CombatHealthRegenMultMod": "Combat health regeneration multiplier modifier",
            "CombatHealthRegenMultPowerMod": "Combat health regeneration multiplier power modifier",
            "StaminaRateMult": "Stamina rate multiplier",
            "HealRatePowerMod": "Heal rate power modifier",
            "MagickaRateMod": "Magicka rate modifier",
            "GrabActorOffset": "Grab actor offset",
            "Grabbed": "Grabbed",
            #";/Cannot find the name of this AVI/;": "Cannot find the name of this AVI",
            "ReflectDamage": "Reflect damage"
            }
            return items

    class PapyrusSkseActorValueInfoIdSuggestionsCommand(SublimePapyrus.PapyrusShowSuggestionsCommand):
        def get_items(self, **args):
            items = {
            0: "Aggression",
            1: "Confidence",
            2: "Energy",
            3: "Morality",
            4: "Mood",
            5: "Assistance",
            6: "One-handed",
            7: "Two-handed",
            8: "Marksman",
            9: "Block",
            10: "Smithing",
            11: "Heavy armor",
            12: "Light armor",
            13: "Pickpocket",
            14: "Lockpicking",
            15: "Sneak",
            16: "Alchemy",
            17: "Speech",
            18: "Alteration",
            19: "Conjuration",
            20: "Destruction",
            21: "Mysticism",
            22: "Restoration",
            23: "Enchanting",
            24: "Health",
            25: "Magicka",
            26: "Stamina",
            27: "Heal rate",
            28: "Magicka rate",
            29: "Stamina rate",
            30: "Speed multiplier",
            31: "Inventory weight",
            32: "Carry weight",
            33: "Critical chance",
            34: "Melee damage",
            35: "Unarmed damage",
            36: "Mass",
            37: "Voice points",
            38: "Voice rate",
            39: "Damage resistance",
            40: "Poison resistance",
            41: "Fire resistance",
            42: "Shock resistance",
            43: "Frost resistance",
            44: "Magic resistance",
            45: "Normal weapon resistance",
            46: "Perception condition",
            47: "Endurance condition",
            48: "Left attack condition",
            49: "Right attack condition",
            50: "Left mobility condition",
            51: "Right mobility condition",
            52: "Brain condition",
            53: "Paralysis",
            54: "Invisibility",
            55: "Night eye",
            56: "Detect life range",
            57: "Water breathing",
            58: "Water walking",
            59: "Ignore crippled limbs",
            60: "Fame",
            61: "Infamy",
            62: "Jumping bonus",
            63: "Ward power",
            64: "Equipped item charge",
            65: "Armor perks",
            66: "Shield perks",
            67: "Ward deflection",
            68: "Variable 01",
            69: "Variable 02",
            70: "Variable 03",
            71: "Variable 04",
            72: "Variable 05",
            73: "Variable 06",
            74: "Variable 07",
            75: "Variable 08",
            76: "Variable 09",
            77: "Variable 10",
            78: "Bow speed bonus",
            79: "Favor active",
            80: "Favors per day",
            81: "Favors per day timer",
            82: "Equipped staff charge",
            83: "Absorb chance",
            84: "Blindness",
            85: "Weapon speed multiplier",
            86: "Shout recovery multiplier",
            87: "Bow stagger bonus",
            88: "Telekinesis",
            89: "Favor points bonus",
            90: "Last bribed or intimidated",
            91: "Last flattered",
            92: "Muffled",
            93: "Bypass vendor stolen check",
            94: "Bypass vendor keyword check",
            95: "Waiting for player",
            96: "One-handed modifier",
            97: "Two-handed modifier",
            98: "Marksman modifier",
            99: "Block modifier",
            100: "Smithing modifier",
            101: "Heavy armor modifier",
            102: "Light armor modifier",
            103: "Pickpocket modifier",
            104: "Lockpicking modifier",
            105: "Sneak modifier",
            106: "Alchemy modifier",
            107: "Speech modifier",
            108: "Alteration modifier",
            109: "Conjuration modifier",
            110: "Destruction modifier",
            111: "Illusion modifier",
            112: "Restoration modifier",
            113: "Enchanting modifier",
            114: "One-handed skill advance",
            115: "Two-handed skill advance",
            116: "Marksman skill advance",
            117: "Block skill advance",
            118: "Smithing skill advance",
            119: "Heavy armor skill advance",
            120: "Light armor skill advance",
            121: "Pickpocket skill advance",
            122: "Lockpicking skill advance",
            123: "Sneak skill advance",
            124: "Alchemy skill advance",
            125: "Speech skill advance",
            126: "Alteration skill advance",
            127: "Conjuration skill advance",
            128: "Destruction skill advance",
            129: "Illusion skill advance",
            130: "Restoration skill advance",
            131: "Enchanting skill advance",
            132: "Left weapon speed multiplier",
            133: "Dragon souls",
            134: "Combat health regeneration multiplier",
            135: "One-handed power modifier",
            136: "Two-handed power modifier",
            137: "Marksman power modifier",
            138: "Block power modifier",
            139: "Smithing power modifier",
            140: "Heavy armor power modifier",
            141: "Light armor power modifier",
            142: "Pickpocket power modifier",
            143: "Lockpicking power modifier",
            144: "Sneak power modifier",
            145: "Alchemy power modifier",
            146: "Speech power modifier",
            147: "Alteration power modifier",
            148: "Conjuration power modifier",
            149: "Destruction power modifier",
            150: "Illusion power modifier",
            151: "Restoration power modifier",
            152: "Enchanting power modifier",
            153: "Dragon Rend",
            154: "Attack damage multiplier",
            155: "Combat health regeneration multiplier modifier",
            156: "Combat health regeneration multiplier power modifier",
            157: "Stamina rate multiplier",
            158: "Heal rate power modifier",
            159: "Magicka rate modifier",
            160: "Grab actor offset",
            161: "Grabbed",
            #162: "Cannot find the name of this AVI",
            163: "Reflect damage"
            }
            return items