import sublime, sublime_plugin, sys
PYTHON_VERSION = sys.version_info
if PYTHON_VERSION[0] == 3:
    from SublimePapyrus import SublimePapyrus

    class PapyrusSkseMenuSuggestionsCommand(SublimePapyrus.PapyrusShowSuggestionsCommand):
        def get_items(self, **args):
            items = {
            "BarterMenu": "Barter",
            "Book Menu": "Book",
            "Console Native UI Menu": "Console native UI",
            "Console": "Console",
            "ContainerMenu": "Container",
            "Crafting Menu": "Crafting",
            "Credits Menu": "Credits",
            "Cursor Menu": "Cursor",
            "CustomMenu": "Custom",
            "Debug Text Menu": "Debug text",
            "Dialogue Menu": "Dialogue",
            "Fader Menu": "Fader",
            "FavoritesMenu": "Favorites",
            "GiftMenu": "Gift",
            "HUD Menu": "HUD",
            "InventoryMenu": "Inventory",
            "Journal Menu": "Journal",
            "Kinect Menu": "Kinect",
            "LevelUp Menu": "Level up",
            "Loading Menu": "Loading",
            "Lockpicking Menu": "Lockpicking",
            "MagicMenu": "Magic",
            "Main Menu": "Main menu",
            "MapMenu": "Map",
            "MessageBoxMenu": "Message box",
            "Mist Menu": "Mist",
            "Overlay Interaction Menu": "Overlay interaction",
            "Overlay Menu": "Overlay",
            "Quantity Menu": "Quantity",
            "RaceSex Menu": "Race (character creation)",
            "Sleep/Wait Menu": "Sleep/wait",
            "StatsMenu": "Stats",
            "TitleSequence Menu": "Title sequence",
            "Top Menu": "Top",
            "Training Menu": "Training",
            "Tutorial Menu": "Tutorial",
            "TweenMenu": "Tween"
            }
            return items

    class PapyrusSkseKeycodeSuggestionsCommand(SublimePapyrus.PapyrusShowSuggestionsCommand):
        def get_items(self, **args):
            items = {
            1: "Escape",
            2: "1",
            3: "2",
            4: "3",
            5: "4",
            6: "5",
            7: "6",
            8: "7",
            9: "8",
            10: "9",
            11: "0",
            12: "Minus",
            13: "Equals",
            14: "Backspace",
            15: "Tab",
            16: "Q",
            17: "W",
            18: "E",
            19: "R",
            20: "T",
            21: "Y",
            22: "U",
            23: "I",
            24: "O",
            25: "P",
            26: "Left Bracket",
            27: "Right Bracket",
            28: "Enter",
            29: "Left Control",
            30: "A",
            31: "S",
            32: "D",
            33: "F",
            34: "G",
            35: "H",
            36: "J",
            37: "K",
            38: "L",
            39: "Semicolon",
            40: "Apostrophe",
            41: "Tilde",
            42: "Left Shift",
            43: "Back Slash",
            44: "Z",
            45: "X",
            46: "C",
            47: "V",
            48: "B",
            49: "N",
            50: "M",
            51: "Comma",
            52: "Period",
            53: "Forward Slash",
            54: "Right Shift",
            55: "NUM*",
            56: "Left Alt",
            57: "Spacebar",
            58: "Caps Lock",
            59: "F1",
            60: "F2",
            61: "F3",
            62: "F4",
            63: "F5",
            64: "F6",
            65: "F7",
            66: "F8",
            67: "F9",
            68: "F10",
            69: "Num Lock",
            70: "Scroll Lock",
            71: "NUM7",
            72: "NUM8",
            73: "NUM9",
            74: "NUM-",
            75: "NUM4",
            76: "NUM5",
            77: "NUM6",
            78: "NUM+",
            79: "NUM1",
            80: "NUM2",
            81: "NUM3",
            82: "NUM0",
            83: "NUM.",
            87: "F11",
            88: "F12",
            156: "NUM Enter",
            157: "Right Control",
            181: "NUM/",
            184: "Right Alt",
            199: "Home",
            200: "Up Arrow",
            201: "PgUp",
            203: "Left Arrow",
            205: "Right Arrow",
            207: "End",
            208: "Down Arrow",
            209: "PgDown",
            210: "Insert",
            211: "Delete",
            256: "Left Mouse Button",
            257: "Right Mouse Button",
            258: "Middle/Wheel Mouse Button",
            259: "Mouse Button 3",
            260: "Mouse Button 4",
            261: "Mouse Button 5",
            262: "Mouse Button 6",
            263: "Mouse Button 7",
            264: "Mouse Wheel Up",
            265: "Mouse Wheel Down",
            266: "D-pad Up (Gamepad)",
            267: "D-pad Down (Gamepad)",
            268: "D-pad Left (Gamepad)",
            269: "D-pad Right (Gamepad)",
            270: "Start (Gamepad)",
            271: "Back (Gamepad)",
            272: "Left thumbstick (Gamepad)",
            273: "Right thumbstick (Gamepad)",
            274: "Left shoulder (Gamepad)",
            275: "Right shoulder (Gamepad)",
            276: "A (Gamepad)",
            277: "B (Gamepad)",
            278: "X (Gamepad)",
            279: "Y (Gamepad)",
            280: "Left trigger (Gamepad)",
            281: "Right trigger (Gamepad)"
            }
            return items

    class PapyrusSkseControlSuggestionsCommand(SublimePapyrus.PapyrusShowSuggestionsCommand):
        def get_items(self, **args):
            items = {
            "Activate": "Activate",
            "Auto-Move": "Auto-move",
            "Back": "Back",
            "CameraPath": "Camera Path",
            "Console": "Console",
            "Favorites": "Favorites",
            "Forward": "Forward",
            "Hotkey1": "Hotkey 1",
            "Hotkey2": "Hotkey 2",
            "Hotkey3": "Hotkey 3",
            "Hotkey4": "Hotkey 4",
            "Hotkey5": "Hotkey 5",
            "Hotkey6": "Hotkey 6",
            "Hotkey7": "Hotkey 7",
            "Hotkey8": "Hotkey 8",
            "Journal": "Journal",
            "Jump": "Jump",
            "Left Attack/Block": "Left Attack/Block",
            "Look": "Look",
            "Move": "Move",
            "Multi-Screenshot": "Multi-screenshot",
            "Pause": "Pause",
            "Quick Inventory": "Quick Inventory",
            "Quick Magic": "Quick Magic",
            "Quick Map": "Quick Map",
            "Quick Stats": "Quick Stats",
            "Quickload": "Quick Load",
            "Quicksave": "Quick Save",
            "Ready Weapon": "Ready Weapon",
            "Right Attack/Block": "Right Attack/Block",
            "Run": "Run",
            "Screenshot": "Screenshot",
            "Shout": "Shout",
            "Sneak": "Sneak",
            "Sprint": "Sprint",
            "Strafe Left": "Strafe Left",
            "Strafe Right": "Strafe Right",
            "Toggle Always Run": "Toggle Always Run",
            "Toggle POV": "Toggle POV",
            "Tween Menu": "Tween Menu",
            "Wait": "Wait",
            "Zoom In": "Zoom In",
            "Zoom Out": "Zoom Out"
            }
            return items
