import sublime, sublime_plugin, sys, os
PYTHON_VERSION = sys.version_info
if PYTHON_VERSION[0] == 2:
    import imp
    mainPackage = os.path.join(os.path.split(os.getcwd())[0], "SublimePapyrus", "SublimePapyrus.py")
    imp.load_source("SublimePapyrus", mainPackage)
    del mainPackage
    import SublimePapyrus
if PYTHON_VERSION[0] == 3:
    from SublimePapyrus import SublimePapyrus

class PapyrusSkyrimActorValueSuggestionsCommand(SublimePapyrus.PapyrusShowSuggestionsCommand):
    def get_items(self, **args):
        items = {
		"Aggression": "Aggression",
		"Alchemy": "Alchemy",
		"Alteration modifier": "AlterationMod",
		"Alteration power modifier": "AlterationPowerMod",
		"Alteration": "Alteration",
		"Armor perks": "ArmorPerks",
		"Assistance": "Assistance",
		"Attack damage multiplier": "AttackDamageMult",
		"Block": "Block",
		"Bow speed bonus": "BowSpeedBonus",
		"Brain condition": "BrainCondition",
		"Bypass vendor keyword check": "BypassVendorKeywordCheck",
		"Bypass vendor stolen check": "BypassVendorStolenCheck",
		"Carry weight": "CarryWeight",
		"Combat health regeneration multiplier modifier": "CombatHealthRegenMultMod",
		"Combat health regeneration multiplier power modifier": "CombatHealthRegenMultPowerMod",
		"Confidence": "Confidence",
		"Conjuration modifier": "ConjurationMod",
		"Conjuration power modifier": "ConjurationPowerMod",
		"Conjuration": "Conjuration",
		"Critical chance": "CritChance",
		"Damage resistance": "DamageResist",
		"Destruction modifier": "DestructionMod",
		"Destruction power modifier": "DestructionPowerMod",
		"Destruction": "Destruction",
		"Detect life range": "DetectLifeRange",
		"Disease resistance": "DiseaseResist",
		"Dragon souls": "DragonSouls",
		"Enchanting": "Enchanting",
		"Endurance condition": "EnduranceCondition",
		"Energy": "Energy",
		"Equipped item charge": "EquippedItemCharge",
		"Equipped staff charge": "EquippedStaffCharge",
		"Fame": "Fame",
		"Favor active": "FavorActive",
		"Favor points bonus": "FavorPointsBonus",
		"Favors per day timer": "FavorsPerDayTimer",
		"Favors per day": "FavorsPerDay",
		"Fire resistance": "FireResist",
		"Frost resistance": "FrostResist",
		"Heal rate": "HealRate",
		"Health": "Health",
		"Heavy armor": "HeavyArmor",
		"Ignore crippled limbs": "IgnoreCrippledLimbs",
		"Illusion modifier": "IllusionMod",
		"Illusion power modifier": "IllusionPowerMod",
		"Illusion": "Illusion",
		"Infamy": "Infamy",
		"Inventory weight": "InventoryWeight",
		"Invisibility": "Invisibility",
		"Jumping bonus": "JumpingBonus",
		"Last bribed or intimidated": "LastBribedIntimidated",
		"Last flattered": "LastFlattered",
		"Left attack condition": "LeftAttackCondition",
		"Left mobility condition": "LeftMobilityCondition",
		"Light armor": "LightArmor",
		"Lockpicking": "Lockpicking",
		"Magic resistance": "MagicResist",
		"Magicka rate": "MagickaRate",
		"Magicka": "Magicka",
		"Marksman": "Marksman",
		"Mass": "Mass",
		"Melee damage": "MeleeDamage",
		"Mood": "Mood",
		"Morality": "Morality",
		"Night eye": "NightEye",
		"One-handed": "OneHanded",
		"Paralysis": "Paralysis",
		"Perception condition": "PerceptionCondition",
		"Pickpocket": "Pickpocket",
		"Poison resistance": "PoisonResist",
		"Restoration modifier": "RestorationMod",
		"Restoration power modifier": "RestorationPowerMod",
		"Restoration": "Restoration",
		"Right attack condition": "RightAttackCondition",
		"Right mobility condition": "RightMobilityCondition",
		"Shield perks": "ShieldPerks",
		"Shock resistance": "ElectricResist",
		"Shout recovery multiplier": "ShoutRecoveryMult",
		"Smithing": "Smithing",
		"Sneak": "Sneak",
		"Speech": "Speechcraft",
		"Speed multiplier": "SpeedMult",
		"Stamina rate": "StaminaRate",
		"Stamina": "Stamina",
		"Two-handed": "TwoHanded",
		"Unarmed damage": "UnarmedDamage",
		"Variable 01": "Variable01",
		"Variable 02": "Variable02",
		"Variable 03": "Variable03",
		"Variable 04": "Variable04",
		"Variable 05": "Variable05",
		"Variable 06": "Variable06",
		"Variable 07": "Variable07",
		"Variable 08": "Variable08",
		"Variable 09": "Variable09",
		"Variable 10": "Variable10",
		"Voice points": "VoicePoints",
		"Voice rate": "VoiceRate",
		"Waiting for player": "WaitingForPlayer",
		"Ward deflection": "WardDeflection",
		"Ward power": "WardPower",
		"Water breating": "WaterBreathing",
		"Water walking": "WaterWalking",
		"Weapon speed multiplier": "WeaponSpeedMult",
        }
        return items

class PapyrusSkyrimFormTypeSuggestionsCommand(SublimePapyrus.PapyrusShowSuggestionsCommand):
    def get_items(self, **args):
    	items = {
    	"(TLOD)": 74,
		"(TOFT)": 86,
		"Acoustic Space (ASPC)": 16,
		"Action (AACT)": 6,
		"Activator (ACTI)": 24,
		"Actor (NPC_)": 43,
		"ActorValueInfo (AVIF)": 95,
		"Addon Node (ADDN)": 94,
		"AI Package (PACK)": 79,
		"Ammo (AMMO)": 42,
		"Animated Object (ANIO)": 83,
		"Apparatus (APPA)": 33,
		"Armor (ARMO)": 26,
		"Armor Addon (ARMA)": 102,
		"Arrow Projectile (PARW)": 64,
		"Art Object (ARTO)": 125,
		"Association Type (ASTP)": 123,
		"Barrier Projectile (PBAR)": 69,
		"Beam Projectile (PBEA)": 66,
		"Body Part Data (BPTD)": 93,
		"Book (BOOK)": 27,
		"Camera Path (CPTH)": 97,
		"Camera Shot (CAMS)": 96,
		"Cell (CELL)": 60,
		"Character": 62,
		"Class (CLAS)": 10,
		"Climate (CLMT)": 55,
		"Collision Layer (COLL)": 132,
		"Color Form (CLFM)": 133,
		"Combat Style (CSTY)": 80,
		"Cone/Voice Projectile (PCON)": 68,
		"Constructible Object (COBJ)": 49,
		"Container (CONT)": 28,
		"Debris (DEBR)": 88,
		"Default Object Manager (DOBJ)": 107,
		"Dialog View (DLVW)": 117,
		"Dialogue Branch (DLBR)": 115,
		"Door (DOOR)": 29,
		"Dual Cast Data (DUAL)": 129,
		"Effect Setting": 18,
		"Effect Shader (EFSH)": 85,
		"Enchantment (ENCH)": 21,
		"Encounter Zone (ECZN)": 103,
		"Equip Slot (EQUP)": 120,
		"Explosion (EXPL)": 87,
		"Eyes (EYES)": 13,
		"Faction (FACT)": 11,
		"Flame Projectile (PLFA)": 67,
		"Flora (FLOR)": 39,
		"Footstep (FSTP)": 110,
		"Footstep Set (FSTS)": 111,
		"FormID List (FLST)": 91,
		"Furniture (FURN)": 40,
		"Game Setting (GMST)": 3,
		"Global Variable (GLOB)": 9,
		"Grass (GRAS)": 37,
		"Grenade Projectile (PGRE)": 65,
		"Group (GRUP)": 2,
		"Hazard (HAZD)": 51,
		"Head Part (HDPT)": 12,
		"Idle (IDLE)": 78,
		"Idle Marker (IDLM)": 47,
		"Image Space (IMGS)": 89,
		"Image Space Modifier (IMAD)": 90,
		"Impact Data (IPCT)": 100,
		"Impact Data Set (IPDS)": 101,
		"Ingredient (INGR)": 30,
		"Key (KEYM)": 45,
		"Keyword (KYWD)": 4,
		"Land Texture (LTEX)": 20,
		"Landscape (LAND)": 72,
		"Leveled Actor (LVLN)": 44,
		"Leveled Item (LVLI)": 53,
		"Leveled Spell (LVLS)": 82,
		"Light (LIGH)": 31,
		"Lighting Template (LGTM)": 108,
		"Load Screen (LSCR)": 81,
		"Location (LCTN)": 104,
		"Location Reference Type (LCRT)": 5,
		"Main File Header (TES4)": 1,
		"Material Object (MATO)": 126,
		"Material Type (MATT)": 99,
		"Menu Icon": 8,
		"Message (MESG)": 105,
		"Miscellaneous Object (MISC)": 32,
		"Missile Projectile (PMIS)": 63,
		"Movable Static (MSTT)": 36,
		"Movement Type (MOVT)": 127,
		"Music Track (MUST)": 116,
		"Music Type (MUSC)": 109,
		"Navigation (NAVI)": 59,
		"Navigation Mesh (NAVM)": 73,
		"None": 0,
		"Note": 48,
		"Object Reference (REFR)": 61,
		"Outfit (OTFT)": 124,
		"Perk (PERK)": 92,
		"Placed Hazard (PHZD)": 70,
		"Potion (ALCH)": 46,
		"Projectile (PROJ)": 50,
		"Quest (QUST)": 77,
		"Race (RACE)": 14,
		"Ragdoll (RGDL)": 106,
		"Region (REGN)": 58,
		"Relationship (RELA)": 121,
		"Reverb Parameter (REVB)": 134,
		"Scene (SCEN)": 122,
		"Script (SCPT)": 19,
		"Scroll Item (SCRL)": 23,
		"Shader Particle Geometry Data (SPGD)": 56,
		"Shout (SHOU)": 119,
		"Skill": 17,
		"Soul Gem (SLGM)": 52,
		"Sound (SOUN)": 15,
		"Sound Category (SNCT)": 130,
		"Sound Descriptor (SNDR)": 128,
		"Sound Output (SOPM)": 131,
		"Spell (SPEL)": 22,
		"Static (STAT)": 34,
		"Static Collection": 35,
		"Story Manager Branch Node (SMBN)": 112,
		"Story Manager Event Node (SMEN)": 114,
		"Story Manager Quest Node (SMQN)": 113,
		"Talking Activator (TACT)": 25,
		"Texture Set (TXST)": 7,
		"Topic (DIAL)": 75,
		"Topic Info (INFO)": 76,
		"Tree (TREE)": 38,
		"Visual/Reference Effect (RFCT)": 57,
		"Voice Type (VTYP)": 98,
		"Water (WATR)": 84,
		"Weapon (WEAP)": 41,
		"Weather (WTHR)": 54,
		"Word of Power (WOOP)": 118,
		"Worldspace (WRLD)": 71
    	}
    	return items